library(reeevr)
library(BCEA)
numberOfRuns = 1000
converter_validate = TRUE
Frontend_A1 = NA
Frontend_B1 = NA
Frontend_C1 = NA
Frontend_D1 = NA
Frontend_E1 = NA
Frontend_F1 = NA
Frontend_G1 = NA
Frontend_A2 = NA
Frontend_B2 = NA
Frontend_C2 = NA
Frontend_D2 = NA
Frontend_E2 = NA
Frontend_F2 = NA
Frontend_G2 = NA
Frontend_A3 = NA
Frontend_B3 = NA
Frontend_C3 = NA
Frontend_D3 = NA
Frontend_E3 = NA
Frontend_F3 = NA
Frontend_G3 = NA
Frontend_A4 = NA
Frontend_B4 = NA
Frontend_C4 = NA
Frontend_D4 = "Inputs"
Frontend_E4 = NA
Frontend_F4 = NA
Frontend_G4 = "Notes"
Frontend_A5 = NA
Frontend_B5 = NA
Frontend_C5 = NA
Frontend_D5 = "Willingness-to-pay"
Frontend_E5 = 20000
Frontend_F5 = NA
Frontend_G5 = NA
Frontend_A6 = NA
Frontend_B6 = NA
Frontend_C6 = NA
Frontend_D6 = "Include MI?"
Frontend_E6 = "Yes"
Frontend_F6 = NA
Frontend_G6 = "Base case includes MI but a sensitivity analysis is to set MI probabilities to zero"
Frontend_A7 = NA
Frontend_B7 = NA
Frontend_C7 = NA
Frontend_D7 = "Outputs"
Frontend_E7 = NA
Frontend_F7 = NA
Frontend_G7 = NA
Frontend_A8 = NA
Frontend_B8 = NA
Frontend_C8 = NA
Frontend_D8 = "ICER Warfarin vs aspirin"
Frontend_F8 = NA
Frontend_G8 = NA
Frontend_A9 = NA
Frontend_B9 = NA
Frontend_C9 = NA
Frontend_D9 = "INB Warfarin vs aspirin"
Frontend_F9 = NA
Frontend_G9 = NA
Inputparameters_A1 = NA
Inputparameters_B1 = NA
Inputparameters_C1 = NA
Inputparameters_D1 = NA
Inputparameters_E1 = NA
Inputparameters_A2 = NA
Inputparameters_B2 = NA
Inputparameters_C2 = NA
Inputparameters_D2 = NA
Inputparameters_E2 = NA
Inputparameters_A3 = NA
Inputparameters_B3 = NA
Inputparameters_C3 = NA
Inputparameters_D3 = "Name"
Inputparameters_E3 = "Value"
Inputparameters_A4 = NA
Inputparameters_B4 = NA
Inputparameters_C4 = NA
Inputparameters_D4 = "Probability stroke aspirin"
Inputparameters_E4 = 0.1
Inputparameters_A5 = NA
Inputparameters_B5 = NA
Inputparameters_C5 = NA
Inputparameters_D5 = "Probability stroke warfarin"
Inputparameters_E5 = 0.025
Inputparameters_A6 = NA
Inputparameters_B6 = NA
Inputparameters_C6 = NA
Inputparameters_D6 = "Probability bleed aspirin"
Inputparameters_E6 = 0.025
Inputparameters_A7 = NA
Inputparameters_B7 = NA
Inputparameters_C7 = NA
Inputparameters_D7 = "Probability bleed warfarin"
Inputparameters_E7 = 0.03
Inputparameters_A8 = NA
Inputparameters_B8 = NA
Inputparameters_C8 = NA
Inputparameters_D8 = "Probability MI aspirin"
Inputparameters_E8_if_1_1 <- function(){
    if(Frontend_E6=="Yes"){
        return(0.05)
    }
    else{
        return(0)
    }
}
Inputparameters_E8 = Inputparameters_E8_if_1_1()
Inputparameters_A9 = NA
Inputparameters_B9 = NA
Inputparameters_C9 = NA
Inputparameters_D9 = "Probability MI warfarin"
Inputparameters_E9_if_1_1 <- function(){
    if(Frontend_E6=="Yes"){
        return(0.01)
    }
    else{
        return(0)
    }
}
Inputparameters_E9 = Inputparameters_E9_if_1_1()
Inputparameters_A10 = NA
Inputparameters_B10 = NA
Inputparameters_C10 = NA
Inputparameters_D10 = "Cost course aspirin"
Inputparameters_E10 = 10
Inputparameters_A11 = NA
Inputparameters_B11 = NA
Inputparameters_C11 = NA
Inputparameters_D11 = "Cost course warfarin"
Inputparameters_E11 = 500
Inputparameters_A12 = NA
Inputparameters_B12 = NA
Inputparameters_C12 = NA
Inputparameters_D12 = "Cost stroke"
Inputparameters_A13 = NA
Inputparameters_B13 = NA
Inputparameters_C13 = NA
Inputparameters_D13 = "Cost bleed"
Inputparameters_E13 = 400
Inputparameters_A14 = NA
Inputparameters_B14 = NA
Inputparameters_C14 = NA
Inputparameters_D14 = "Cost MI"
Inputparameters_E14 = 2000
Inputparameters_A15 = NA
Inputparameters_B15 = NA
Inputparameters_C15 = NA
Inputparameters_D15 = "QALYS stroke"
Inputparameters_A16 = NA
Inputparameters_B16 = NA
Inputparameters_C16 = NA
Inputparameters_D16 = "QALYS bleed"
Inputparameters_E16 = 12
Inputparameters_A17 = NA
Inputparameters_B17 = NA
Inputparameters_C17 = NA
Inputparameters_D17 = "QALYS well"
Inputparameters_E17 = 20
Inputparameters_A18 = NA
Inputparameters_B18 = NA
Inputparameters_C18 = NA
Inputparameters_D18 = "QALYS MI"
Inputparameters_E18 = 12
Costing_A1 = NA
Costing_B1 = NA
Costing_C1 = NA
Costing_D1 = NA
Costing_E1 = NA
Costing_A2 = NA
Costing_B2 = NA
Costing_C2 = NA
Costing_D2 = NA
Costing_E2 = NA
Costing_A3 = NA
Costing_B3 = NA
Costing_C3 = NA
Costing_D3 = "Cost component"
Costing_E3 = "Cost"
Costing_A4 = NA
Costing_B4 = NA
Costing_C4 = NA
Costing_D4 = "5 nights hospital"
Costing_E4 = 5000
Costing_A5 = NA
Costing_B5 = NA
Costing_C5 = NA
Costing_D5 = "2 consultant visits"
Costing_E5 = 400
Costing_A6 = NA
Costing_B6 = NA
Costing_C6 = NA
Costing_D6 = "5 nurse visits"
Costing_E6 = 100
Costing_A7 = NA
Costing_B7 = NA
Costing_C7 = NA
Costing_D7 = "3 GP visits"
Costing_E7 = 150
Costing_A8 = NA
Costing_B8 = NA
Costing_C8 = NA
Costing_D8 = "occupational therapy"
Costing_E8 = 100
Costing_A9 = NA
Costing_B9 = NA
Costing_C9 = NA
Costing_D9 = "counselling"
Costing_E9 = 100
QALYs_A1 = NA
QALYs_B1 = NA
QALYs_C1 = NA
QALYs_D1 = NA
QALYs_A2 = NA
QALYs_B2 = NA
QALYs_C2 = "We found twenty publications giving different QALYs on stroke for UK patients"
QALYs_D2 = NA
QALYs_A3 = NA
QALYs_B3 = NA
QALYs_C3 = "Study"
QALYs_D3 = "QALYs on stroke"
QALYs_A4 = NA
QALYs_B4 = NA
QALYs_C4 = 1
QALYs_D4 = 14
QALYs_A5 = NA
QALYs_B5 = NA
QALYs_C5 = 2
QALYs_D5 = 15
QALYs_A6 = NA
QALYs_B6 = NA
QALYs_C6 = 3
QALYs_D6 = 12
QALYs_A7 = NA
QALYs_B7 = NA
QALYs_C7 = 4
QALYs_D7 = 16
QALYs_A8 = NA
QALYs_B8 = NA
QALYs_C8 = 5
QALYs_D8 = 14
QALYs_A9 = NA
QALYs_B9 = NA
QALYs_C9 = 6
QALYs_D9 = 14
QALYs_A10 = NA
QALYs_B10 = NA
QALYs_C10 = 7
QALYs_D10 = 15
QALYs_A11 = NA
QALYs_B11 = NA
QALYs_C11 = 8
QALYs_D11 = 13
QALYs_A12 = NA
QALYs_B12 = NA
QALYs_C12 = 9
QALYs_D12 = 12
QALYs_A13 = NA
QALYs_B13 = NA
QALYs_C13 = 10
QALYs_D13 = 16
QALYs_A14 = NA
QALYs_B14 = NA
QALYs_C14 = 11
QALYs_D14 = 16
QALYs_A15 = NA
QALYs_B15 = NA
QALYs_C15 = 12
QALYs_D15 = 10
QALYs_A16 = NA
QALYs_B16 = NA
QALYs_C16 = 13
QALYs_D16 = 14
QALYs_A17 = NA
QALYs_B17 = NA
QALYs_C17 = 14
QALYs_D17 = 15
QALYs_A18 = NA
QALYs_B18 = NA
QALYs_C18 = 15
QALYs_D18 = 14
QALYs_A19 = NA
QALYs_B19 = NA
QALYs_C19 = 16
QALYs_D19 = 13
QALYs_A20 = NA
QALYs_B20 = NA
QALYs_C20 = 17
QALYs_D20 = 17
QALYs_A21 = NA
QALYs_B21 = NA
QALYs_C21 = 18
QALYs_D21 = 12
QALYs_A22 = NA
QALYs_B22 = NA
QALYs_C22 = 19
QALYs_D22 = 18
QALYs_A23 = NA
QALYs_B23 = NA
QALYs_C23 = 20
QALYs_D23 = 14
Engine_A1 = NA
Engine_B1 = NA
Engine_C1 = NA
Engine_D1 = NA
Engine_E1 = NA
Engine_F1 = NA
Engine_G1 = NA
Engine_A2 = NA
Engine_B2 = NA
Engine_C2 = NA
Engine_D2 = NA
Engine_E2 = NA
Engine_F2 = NA
Engine_G2 = NA
Engine_A3 = NA
Engine_B3 = NA
Engine_C3 = NA
Engine_D3 = NA
Engine_E3 = NA
Engine_F3 = NA
Engine_G3 = NA
Engine_A4 = NA
Engine_B4 = NA
Engine_C4 = NA
Engine_D4 = NA
Engine_E4 = "Aspirin"
Engine_F4 = "Warfarin"
Engine_G4 = "Warfafrin vs aspirin"
Engine_A5 = NA
Engine_B5 = NA
Engine_C5 = NA
Engine_D5 = "Total costs"
Engine_A6 = NA
Engine_B6 = NA
Engine_C6 = NA
Engine_D6 = "Total QALYs"
Engine_A7 = NA
Engine_B7 = NA
Engine_C7 = NA
Engine_D7 = "Net benefit"
willingness_to_pay = Frontend_E5
Inputparameters_E12 = excel_sum(list(Costing_E4, Costing_E5, Costing_E6, Costing_E7, Costing_E8, Costing_E9))
Inputparameters_E15 = excel_average(list(QALYs_D4, QALYs_D5, QALYs_D6, QALYs_D7, QALYs_D8, QALYs_D9, QALYs_D10, QALYs_D11, QALYs_D12, QALYs_D13, QALYs_D14, QALYs_D15, QALYs_D16, QALYs_D17, QALYs_D18, QALYs_D19, QALYs_D20, QALYs_D21, QALYs_D22, QALYs_D23))
Engine_E5 = Inputparameters_E10 + Inputparameters_E6 * Inputparameters_E13 + Inputparameters_E4 * Inputparameters_E12 + Inputparameters_E8 * Inputparameters_E14
Engine_F5 = Inputparameters_E11 + Inputparameters_E7 * Inputparameters_E13 + Inputparameters_E5 * Inputparameters_E12 + Inputparameters_E9 + Inputparameters_E14
Engine_G5 = Engine_F5 - Engine_E5
Engine_E6 = Inputparameters_E6 * Inputparameters_E16 + Inputparameters_E4 * Inputparameters_E15 + ( 1 - Inputparameters_E6 - Inputparameters_E4 - Inputparameters_E8 ) * Inputparameters_E17 + Inputparameters_E8 * Inputparameters_E18
Engine_F6 = Inputparameters_E7 * Inputparameters_E16 + Inputparameters_E5 * Inputparameters_E15 + ( 1 - Inputparameters_E7 - Inputparameters_E5 - Inputparameters_E9 ) * Inputparameters_E17 + Inputparameters_E9 * Inputparameters_E18
Engine_G6 = Engine_F6 - Engine_E6
Engine_E7 = Engine_E6 * willingness_to_pay - Engine_E5
Engine_F7 = Engine_F6 * willingness_to_pay - Engine_F5
Engine_G7 = Engine_F7 - Engine_E7
Frontend_E8 = Engine_G5 / Engine_G6
Frontend_E9 = Engine_G7
