library(reeevr)
library(BCEA)
numberOfRuns = 1000
converter_validate = TRUE
Frontend_A1 = NA
Frontend_B1 = NA
Frontend_C1 = NA
Frontend_D1 = NA
Frontend_E1 = NA
Frontend_A2 = NA
Frontend_B2 = NA
Frontend_C2 = NA
Frontend_D2 = NA
Frontend_E2 = NA
Frontend_A3 = NA
Frontend_B3 = NA
Frontend_C3 = NA
Frontend_D3 = NA
Frontend_E3 = NA
Frontend_A4 = NA
Frontend_B4 = NA
Frontend_C4 = NA
Frontend_D4 = "Inputs"
Frontend_E4 = NA
Frontend_A5 = NA
Frontend_B5 = NA
Frontend_C5 = NA
Frontend_D5 = "Willingness-to-pay"
Frontend_E5 = 20000
Frontend_A6 = NA
Frontend_B6 = NA
Frontend_C6 = NA
Frontend_D6 = "Outputs"
Frontend_E6 = NA
Frontend_A7 = NA
Frontend_B7 = NA
Frontend_C7 = NA
Frontend_D7 = "ICER Warfarin vs aspirin"
Frontend_A8 = NA
Frontend_B8 = NA
Frontend_C8 = NA
Frontend_D8 = "INB Warfarin vs aspirin"
Inputparameters_A1 = NA
Inputparameters_B1 = NA
Inputparameters_C1 = NA
Inputparameters_D1 = NA
Inputparameters_E1 = NA
Inputparameters_A2 = NA
Inputparameters_B2 = NA
Inputparameters_C2 = NA
Inputparameters_D2 = NA
Inputparameters_E2 = NA
Inputparameters_A3 = NA
Inputparameters_B3 = NA
Inputparameters_C3 = NA
Inputparameters_D3 = "Name"
Inputparameters_E3 = "Value"
Inputparameters_A4 = NA
Inputparameters_B4 = NA
Inputparameters_C4 = NA
Inputparameters_D4 = "Probability stroke aspirin"
Inputparameters_E4 = 0.1
Inputparameters_A5 = NA
Inputparameters_B5 = NA
Inputparameters_C5 = NA
Inputparameters_D5 = "Probability stroke warfarin"
Inputparameters_E5 = 0.05
Inputparameters_A6 = NA
Inputparameters_B6 = NA
Inputparameters_C6 = NA
Inputparameters_D6 = "Probability bleed aspirin"
Inputparameters_E6 = 0.025
Inputparameters_A7 = NA
Inputparameters_B7 = NA
Inputparameters_C7 = NA
Inputparameters_D7 = "Probability bleed warfarin"
Inputparameters_E7 = 0.05
Inputparameters_A8 = NA
Inputparameters_B8 = NA
Inputparameters_C8 = NA
Inputparameters_D8 = "Cost course aspirin"
Inputparameters_E8 = 10
Inputparameters_A9 = NA
Inputparameters_B9 = NA
Inputparameters_C9 = NA
Inputparameters_D9 = "Cost course warfarin"
Inputparameters_E9 = 500
Inputparameters_A10 = NA
Inputparameters_B10 = NA
Inputparameters_C10 = NA
Inputparameters_D10 = "Cost stroke"
Inputparameters_E10 = 800
Inputparameters_A11 = NA
Inputparameters_B11 = NA
Inputparameters_C11 = NA
Inputparameters_D11 = "Cost bleed"
Inputparameters_E11 = 400
Inputparameters_A12 = NA
Inputparameters_B12 = NA
Inputparameters_C12 = NA
Inputparameters_D12 = "QALYS stroke"
Inputparameters_E12 = 14
Inputparameters_A13 = NA
Inputparameters_B13 = NA
Inputparameters_C13 = NA
Inputparameters_D13 = "QALYS bleed"
Inputparameters_E13 = 12
Inputparameters_A14 = NA
Inputparameters_B14 = NA
Inputparameters_C14 = NA
Inputparameters_D14 = "QALYS well"
Inputparameters_E14 = 20
Engine_A1 = NA
Engine_B1 = NA
Engine_C1 = NA
Engine_D1 = NA
Engine_E1 = NA
Engine_F1 = NA
Engine_G1 = NA
Engine_A2 = NA
Engine_B2 = NA
Engine_C2 = NA
Engine_D2 = NA
Engine_E2 = NA
Engine_F2 = NA
Engine_G2 = NA
Engine_A3 = NA
Engine_B3 = NA
Engine_C3 = NA
Engine_D3 = NA
Engine_E3 = NA
Engine_F3 = NA
Engine_G3 = NA
Engine_A4 = NA
Engine_B4 = NA
Engine_C4 = NA
Engine_D4 = NA
Engine_E4 = "Aspirin"
Engine_F4 = "Warfarin"
Engine_G4 = "Warfafrin vs aspirin"
Engine_A5 = NA
Engine_B5 = NA
Engine_C5 = NA
Engine_D5 = "Total costs"
Engine_E5 = Inputparameters_E8 + Inputparameters_E6 * Inputparameters_E11 + Inputparameters_E4 * Inputparameters_E10
Engine_F5 = Inputparameters_E9 + Inputparameters_E7 * Inputparameters_E11 + Inputparameters_E5 * Inputparameters_E10
Engine_G5 = Engine_F5 - Engine_E5
Engine_A6 = NA
Engine_B6 = NA
Engine_C6 = NA
Engine_D6 = "Total QALYs"
Engine_E6 = Inputparameters_E6 * Inputparameters_E13 + Inputparameters_E4 * Inputparameters_E12 + ( 1 - Inputparameters_E6 - Inputparameters_E4 ) * Inputparameters_E14
Engine_F6 = Inputparameters_E7 * Inputparameters_E13 + Inputparameters_E5 * Inputparameters_E12 + ( 1 - Inputparameters_E7 - Inputparameters_E5 ) * Inputparameters_E14
Engine_G6 = Engine_F6 - Engine_E6
Engine_A7 = NA
Engine_B7 = NA
Engine_C7 = NA
Engine_D7 = "Net benefit"
willingness_to_pay = Frontend_E5
Frontend_E7 = Engine_G5 / Engine_G6
Engine_E7 = Engine_E6 * willingness_to_pay - Engine_E5
Engine_F7 = Engine_F6 * willingness_to_pay - Engine_F5
Engine_G7 = Engine_F7 - Engine_E7
Frontend_E8 = Engine_G7
