library(reeevr)
library(BCEA)
numberOfRuns = 100000
converter_validate = FALSE
Modelsettings_N13 = 20000
Modelsettings_N14 = 0.03
Modelsettings_N15 = 0.03
Modelparameters_M9 = 0.1
Modelparameters_M10 = 0.025
Modelparameters_M11 = 0.975
Modelparameters_G16 = 0.8
Modelparameters_Q16 = 4
Modelparameters_G17 = 0.2
Modelparameters_Q17 = 1
Modelparameters_G18 = 1
Modelparameters_N18 = NA
Modelparameters_O18 = NA
Modelparameters_P18 = NA
Modelparameters_Q18 = 1
Modelparameters_R18 = excel_choose(Modelparameters_Q18,Modelparameters_G18,Modelparameters_N18,Modelparameters_O18,Modelparameters_P18)
Modelparameters_G19 = 0.7
Modelparameters_Q19 = 4
Modelparameters_G20 = 0.3
Modelparameters_Q20 = 1
Modelparameters_G21 = 1
Modelparameters_N21 = NA
Modelparameters_O21 = NA
Modelparameters_P21 = NA
Modelparameters_Q21 = 1
Modelparameters_R21 = excel_choose(Modelparameters_Q21,Modelparameters_G21,Modelparameters_N21,Modelparameters_O21,Modelparameters_P21)
Modelparameters_G23 = 200
Modelparameters_Q23 = 4
Modelparameters_G24 = 800
Modelparameters_Q24 = 4
Modelparameters_G25 = 600
Modelparameters_Q25 = 4
Modelparameters_G26 = 250
Modelparameters_Q26 = 4
Modelparameters_G28 = 0.98
Modelparameters_Q28 = 4
Modelparameters_G29 = 0.56
Modelparameters_Q29 = 4
ModelengineA_G12 = 1
ModelengineA_H12 = 0
ModelengineA_E13 = 1
ModelengineA_F13 = 1
ModelengineA_E14 = 2
ModelengineA_F14 = 1
ModelengineA_E15 = 3
ModelengineA_F15 = 1
ModelengineA_E16 = 4
ModelengineA_F16 = 1
ModelengineA_E17 = 5
ModelengineA_F17 = 1
ModelengineA_E18 = 6
ModelengineA_F18 = 1
ModelengineA_E19 = 7
ModelengineA_F19 = 1
ModelengineA_E20 = 8
ModelengineA_F20 = 1
ModelengineA_E21 = 9
ModelengineA_F21 = 1
ModelengineA_E22 = 10
ModelengineA_F22 = 1
ModelengineB_G12 = 1
ModelengineB_H12 = 0
ModelengineB_E13 = 1
ModelengineB_F13 = 1
ModelengineB_E14 = 2
ModelengineB_F14 = 1
ModelengineB_E15 = 3
ModelengineB_F15 = 1
ModelengineB_E16 = 4
ModelengineB_F16 = 1
ModelengineB_E17 = 5
ModelengineB_F17 = 1
ModelengineB_E18 = 6
ModelengineB_F18 = 1
ModelengineB_E19 = 7
ModelengineB_F19 = 1
ModelengineB_E20 = 8
ModelengineB_F20 = 1
ModelengineB_E21 = 9
ModelengineB_F21 = 1
ModelengineB_E22 = 10
ModelengineB_F22 = 1
discount_cost = Modelsettings_N14
discount_healthOutcome = Modelsettings_N15
p_lower = Modelparameters_M10
p_se = Modelparameters_M9
p_ss_A = Modelparameters_R18
p_ss_B = Modelparameters_R21
p_upper = Modelparameters_M11
willingness_to_pay = Modelsettings_N13
Modelparameters_H16 = Modelparameters_G16 * p_se
Modelparameters_L16 = excel_iferror((Modelparameters_G16*(Modelparameters_G16*(1-Modelparameters_G16)/(Modelparameters_H16^2)-1)),"")
Modelparameters_M16 = excel_iferror(Modelparameters_L16*(1-Modelparameters_G16)/Modelparameters_G16,"")
Modelparameters_N16 = qbeta(p_lower,Modelparameters_L16,Modelparameters_M16)
Modelparameters_O16 = qbeta(p_upper,Modelparameters_L16,Modelparameters_M16)
Modelparameters_P16 = excel_iferror(qbeta(excel_rand(numberOfRuns, converter_validate),Modelparameters_L16,Modelparameters_M16),Modelparameters_G16)
Modelparameters_R16 = excel_choose(Modelparameters_Q16,Modelparameters_G16,Modelparameters_N16,Modelparameters_O16,Modelparameters_P16)
Modelparameters_H17 = Modelparameters_G17 * p_se
Modelparameters_L17 = excel_iferror((Modelparameters_G17*(Modelparameters_G17*(1-Modelparameters_G17)/(Modelparameters_H17^2)-1)),"")
Modelparameters_M17 = excel_iferror(Modelparameters_L17*(1-Modelparameters_G17)/Modelparameters_G17,"")
Modelparameters_N17 = qbeta(p_lower,Modelparameters_L17,Modelparameters_M17)
Modelparameters_O17 = qbeta(p_upper,Modelparameters_L17,Modelparameters_M17)
Modelparameters_P17 = excel_iferror(qbeta(excel_rand(numberOfRuns, converter_validate),Modelparameters_L17,Modelparameters_M17),Modelparameters_G17)
Modelparameters_R17 = excel_choose(Modelparameters_Q17,Modelparameters_G17,Modelparameters_N17,Modelparameters_O17,Modelparameters_P17)
Modelparameters_H19 = Modelparameters_G19 * p_se
Modelparameters_L19 = excel_iferror((Modelparameters_G19*(Modelparameters_G19*(1-Modelparameters_G19)/(Modelparameters_H19^2)-1)),"")
Modelparameters_M19 = excel_iferror(Modelparameters_L19*(1-Modelparameters_G19)/Modelparameters_G19,"")
Modelparameters_N19 = qbeta(p_lower,Modelparameters_L19,Modelparameters_M19)
Modelparameters_O19 = qbeta(p_upper,Modelparameters_L19,Modelparameters_M19)
Modelparameters_P19 = excel_iferror(qbeta(excel_rand(numberOfRuns, converter_validate),Modelparameters_L19,Modelparameters_M19),Modelparameters_G19)
Modelparameters_R19 = excel_choose(Modelparameters_Q19,Modelparameters_G19,Modelparameters_N19,Modelparameters_O19,Modelparameters_P19)
Modelparameters_H20 = Modelparameters_G20 * p_se
Modelparameters_L20 = excel_iferror((Modelparameters_G20*(Modelparameters_G20*(1-Modelparameters_G20)/(Modelparameters_H20^2)-1)),"")
Modelparameters_M20 = excel_iferror(Modelparameters_L20*(1-Modelparameters_G20)/Modelparameters_G20,"")
Modelparameters_N20 = qbeta(p_lower,Modelparameters_L20,Modelparameters_M20)
Modelparameters_O20 = qbeta(p_upper,Modelparameters_L20,Modelparameters_M20)
Modelparameters_P20 = excel_iferror(qbeta(excel_rand(numberOfRuns, converter_validate),Modelparameters_L20,Modelparameters_M20),Modelparameters_G20)
Modelparameters_R20 = excel_choose(Modelparameters_Q20,Modelparameters_G20,Modelparameters_N20,Modelparameters_O20,Modelparameters_P20)
Modelparameters_H23 = Modelparameters_G23 * p_se
Modelparameters_M23 = Modelparameters_H23 ^ 2 / Modelparameters_G23
Modelparameters_H24 = Modelparameters_G24 * p_se
Modelparameters_M24 = Modelparameters_H24 ^ 2 / Modelparameters_G24
Modelparameters_H25 = Modelparameters_G25 * p_se
Modelparameters_M25 = Modelparameters_H25 ^ 2 / Modelparameters_G25
Modelparameters_H26 = Modelparameters_G26 * p_se
Modelparameters_M26 = Modelparameters_H26 ^ 2 / Modelparameters_G26
Modelparameters_H28 = Modelparameters_G28 * p_se
Modelparameters_L28 = excel_iferror((Modelparameters_G28*(Modelparameters_G28*(1-Modelparameters_G28)/(Modelparameters_H28^2)-1)),"")
Modelparameters_M28 = excel_iferror(Modelparameters_L28*(1-Modelparameters_G28)/Modelparameters_G28,"")
Modelparameters_N28 = qbeta(p_lower,Modelparameters_L28,Modelparameters_M28)
Modelparameters_O28 = qbeta(p_upper,Modelparameters_L28,Modelparameters_M28)
Modelparameters_P28 = excel_iferror(qbeta(excel_rand(numberOfRuns, converter_validate),Modelparameters_L28,Modelparameters_M28),Modelparameters_G28)
Modelparameters_R28 = excel_choose(Modelparameters_Q28,Modelparameters_G28,Modelparameters_N28,Modelparameters_O28,Modelparameters_P28)
Modelparameters_H29 = Modelparameters_G29 * p_se
Modelparameters_L29 = excel_iferror((Modelparameters_G29*(Modelparameters_G29*(1-Modelparameters_G29)/(Modelparameters_H29^2)-1)),"")
Modelparameters_M29 = excel_iferror(Modelparameters_L29*(1-Modelparameters_G29)/Modelparameters_G29,"")
Modelparameters_N29 = qbeta(p_lower,Modelparameters_L29,Modelparameters_M29)
Modelparameters_O29 = qbeta(p_upper,Modelparameters_L29,Modelparameters_M29)
Modelparameters_P29 = excel_iferror(qbeta(excel_rand(numberOfRuns, converter_validate),Modelparameters_L29,Modelparameters_M29),Modelparameters_G29)
Modelparameters_R29 = excel_choose(Modelparameters_Q29,Modelparameters_G29,Modelparameters_N29,Modelparameters_O29,Modelparameters_P29)
p_hh_A = Modelparameters_R16
p_hh_B = Modelparameters_R19
p_hs_A = Modelparameters_R17
p_hs_B = Modelparameters_R20
p_u_h = Modelparameters_R28
p_u_s = Modelparameters_R29
Modelparameters_L23 = Modelparameters_G23 / Modelparameters_M23
Modelparameters_N23 = excel_gammainv(p_lower,Modelparameters_L23,Modelparameters_M23)
Modelparameters_O23 = excel_gammainv(p_upper,Modelparameters_L23,Modelparameters_M23)
Modelparameters_P23 = excel_iferror(excel_gammainv(excel_rand(numberOfRuns, converter_validate),Modelparameters_L23,Modelparameters_M23),Modelparameters_G23)
Modelparameters_R23 = excel_choose(Modelparameters_Q23,Modelparameters_G23,Modelparameters_N23,Modelparameters_O23,Modelparameters_P23)
Modelparameters_L24 = Modelparameters_G24 / Modelparameters_M24
Modelparameters_N24 = excel_gammainv(p_lower,Modelparameters_L24,Modelparameters_M24)
Modelparameters_O24 = excel_gammainv(p_upper,Modelparameters_L24,Modelparameters_M24)
Modelparameters_P24 = excel_iferror(excel_gammainv(excel_rand(numberOfRuns, converter_validate),Modelparameters_L24,Modelparameters_M24),Modelparameters_G24)
Modelparameters_R24 = excel_choose(Modelparameters_Q24,Modelparameters_G24,Modelparameters_N24,Modelparameters_O24,Modelparameters_P24)
Modelparameters_L25 = Modelparameters_G25 / Modelparameters_M25
Modelparameters_N25 = excel_gammainv(p_lower,Modelparameters_L25,Modelparameters_M25)
Modelparameters_O25 = excel_gammainv(p_upper,Modelparameters_L25,Modelparameters_M25)
Modelparameters_P25 = excel_iferror(excel_gammainv(excel_rand(numberOfRuns, converter_validate),Modelparameters_L25,Modelparameters_M25),Modelparameters_G25)
Modelparameters_R25 = excel_choose(Modelparameters_Q25,Modelparameters_G25,Modelparameters_N25,Modelparameters_O25,Modelparameters_P25)
Modelparameters_L26 = Modelparameters_G26 / Modelparameters_M26
Modelparameters_N26 = excel_gammainv(p_lower,Modelparameters_L26,Modelparameters_M26)
Modelparameters_O26 = excel_gammainv(p_upper,Modelparameters_L26,Modelparameters_M26)
Modelparameters_P26 = excel_iferror(excel_gammainv(excel_rand(numberOfRuns, converter_validate),Modelparameters_L26,Modelparameters_M26),Modelparameters_G26)
Modelparameters_R26 = excel_choose(Modelparameters_Q26,Modelparameters_G26,Modelparameters_N26,Modelparameters_O26,Modelparameters_P26)
ModelengineA_K12 = ModelengineA_G12 * p_u_h + ModelengineA_H12 * p_u_s
ModelengineA_O12 = ModelengineA_K12
ModelengineA_G13 = ModelengineA_F13 * ModelengineA_G12 * p_hh_A
ModelengineA_H13 = ModelengineA_F13 * ( ModelengineA_G12 * p_hs_A + ModelengineA_H12 * p_ss_A )
ModelengineA_K13 = ModelengineA_G13 * p_u_h + ModelengineA_H13 * p_u_s
ModelengineA_O13 = excel_iferror(ModelengineA_K13/(1+discount_healthOutcome)^(ModelengineA_E13-1),"")
ModelengineA_G14 = ModelengineA_F14 * ModelengineA_G13 * p_hh_A
ModelengineA_H14 = ModelengineA_F14 * ( ModelengineA_G13 * p_hs_A + ModelengineA_H13 * p_ss_A )
ModelengineA_K14 = ModelengineA_G14 * p_u_h + ModelengineA_H14 * p_u_s
ModelengineA_O14 = excel_iferror(ModelengineA_K14/(1+discount_healthOutcome)^(ModelengineA_E14-1),"")
ModelengineA_G15 = ModelengineA_F15 * ModelengineA_G14 * p_hh_A
ModelengineA_H15 = ModelengineA_F15 * ( ModelengineA_G14 * p_hs_A + ModelengineA_H14 * p_ss_A )
ModelengineA_K15 = ModelengineA_G15 * p_u_h + ModelengineA_H15 * p_u_s
ModelengineA_O15 = excel_iferror(ModelengineA_K15/(1+discount_healthOutcome)^(ModelengineA_E15-1),"")
ModelengineA_G16 = ModelengineA_F16 * ModelengineA_G15 * p_hh_A
ModelengineA_H16 = ModelengineA_F16 * ( ModelengineA_G15 * p_hs_A + ModelengineA_H15 * p_ss_A )
ModelengineA_K16 = ModelengineA_G16 * p_u_h + ModelengineA_H16 * p_u_s
ModelengineA_O16 = excel_iferror(ModelengineA_K16/(1+discount_healthOutcome)^(ModelengineA_E16-1),"")
ModelengineA_G17 = ModelengineA_F17 * ModelengineA_G16 * p_hh_A
ModelengineA_H17 = ModelengineA_F17 * ( ModelengineA_G16 * p_hs_A + ModelengineA_H16 * p_ss_A )
ModelengineA_K17 = ModelengineA_G17 * p_u_h + ModelengineA_H17 * p_u_s
ModelengineA_O17 = excel_iferror(ModelengineA_K17/(1+discount_healthOutcome)^(ModelengineA_E17-1),"")
ModelengineA_G18 = ModelengineA_F18 * ModelengineA_G17 * p_hh_A
ModelengineA_H18 = ModelengineA_F18 * ( ModelengineA_G17 * p_hs_A + ModelengineA_H17 * p_ss_A )
ModelengineA_K18 = ModelengineA_G18 * p_u_h + ModelengineA_H18 * p_u_s
ModelengineA_O18 = excel_iferror(ModelengineA_K18/(1+discount_healthOutcome)^(ModelengineA_E18-1),"")
ModelengineA_G19 = ModelengineA_F19 * ModelengineA_G18 * p_hh_A
ModelengineA_H19 = ModelengineA_F19 * ( ModelengineA_G18 * p_hs_A + ModelengineA_H18 * p_ss_A )
ModelengineA_K19 = ModelengineA_G19 * p_u_h + ModelengineA_H19 * p_u_s
ModelengineA_O19 = excel_iferror(ModelengineA_K19/(1+discount_healthOutcome)^(ModelengineA_E19-1),"")
ModelengineA_G20 = ModelengineA_F20 * ModelengineA_G19 * p_hh_A
ModelengineA_H20 = ModelengineA_F20 * ( ModelengineA_G19 * p_hs_A + ModelengineA_H19 * p_ss_A )
ModelengineA_K20 = ModelengineA_G20 * p_u_h + ModelengineA_H20 * p_u_s
ModelengineA_O20 = excel_iferror(ModelengineA_K20/(1+discount_healthOutcome)^(ModelengineA_E20-1),"")
ModelengineA_G21 = ModelengineA_F21 * ModelengineA_G20 * p_hh_A
ModelengineA_H21 = ModelengineA_F21 * ( ModelengineA_G20 * p_hs_A + ModelengineA_H20 * p_ss_A )
ModelengineA_K21 = ModelengineA_G21 * p_u_h + ModelengineA_H21 * p_u_s
ModelengineA_O21 = excel_iferror(ModelengineA_K21/(1+discount_healthOutcome)^(ModelengineA_E21-1),"")
ModelengineA_G22 = ModelengineA_F22 * ModelengineA_G21 * p_hh_A
ModelengineA_H22 = ModelengineA_F22 * ( ModelengineA_G21 * p_hs_A + ModelengineA_H21 * p_ss_A )
ModelengineA_K22 = ModelengineA_G22 * p_u_h + ModelengineA_H22 * p_u_s
ModelengineA_O22 = excel_iferror(ModelengineA_K22/(1+discount_healthOutcome)^(ModelengineA_E22-1),"")
ModelengineB_K12 = ModelengineB_G12 * p_u_h + ModelengineB_H12 * p_u_s
ModelengineB_O12 = ModelengineB_K12
ModelengineB_G13 = ModelengineB_F13 * ModelengineB_G12 * p_hh_B
ModelengineB_H13 = ModelengineB_F13 * ( ModelengineB_G12 * p_hs_B + ModelengineB_H12 * p_ss_B )
ModelengineB_K13 = ModelengineB_G13 * p_u_h + ModelengineB_H13 * p_u_s
ModelengineB_O13 = excel_iferror(ModelengineB_K13/(1+discount_healthOutcome)^(ModelengineB_E13-1),"")
ModelengineB_G14 = ModelengineB_F14 * ModelengineB_G13 * p_hh_B
ModelengineB_H14 = ModelengineB_F14 * ( ModelengineB_G13 * p_hs_B + ModelengineB_H13 * p_ss_B )
ModelengineB_K14 = ModelengineB_G14 * p_u_h + ModelengineB_H14 * p_u_s
ModelengineB_O14 = excel_iferror(ModelengineB_K14/(1+discount_healthOutcome)^(ModelengineB_E14-1),"")
ModelengineB_G15 = ModelengineB_F15 * ModelengineB_G14 * p_hh_B
ModelengineB_H15 = ModelengineB_F15 * ( ModelengineB_G14 * p_hs_B + ModelengineB_H14 * p_ss_B )
ModelengineB_K15 = ModelengineB_G15 * p_u_h + ModelengineB_H15 * p_u_s
ModelengineB_O15 = excel_iferror(ModelengineB_K15/(1+discount_healthOutcome)^(ModelengineB_E15-1),"")
ModelengineB_G16 = ModelengineB_F16 * ModelengineB_G15 * p_hh_B
ModelengineB_H16 = ModelengineB_F16 * ( ModelengineB_G15 * p_hs_B + ModelengineB_H15 * p_ss_B )
ModelengineB_K16 = ModelengineB_G16 * p_u_h + ModelengineB_H16 * p_u_s
ModelengineB_O16 = excel_iferror(ModelengineB_K16/(1+discount_healthOutcome)^(ModelengineB_E16-1),"")
ModelengineB_G17 = ModelengineB_F17 * ModelengineB_G16 * p_hh_B
ModelengineB_H17 = ModelengineB_F17 * ( ModelengineB_G16 * p_hs_B + ModelengineB_H16 * p_ss_B )
ModelengineB_K17 = ModelengineB_G17 * p_u_h + ModelengineB_H17 * p_u_s
ModelengineB_O17 = excel_iferror(ModelengineB_K17/(1+discount_healthOutcome)^(ModelengineB_E17-1),"")
ModelengineB_G18 = ModelengineB_F18 * ModelengineB_G17 * p_hh_B
ModelengineB_H18 = ModelengineB_F18 * ( ModelengineB_G17 * p_hs_B + ModelengineB_H17 * p_ss_B )
ModelengineB_K18 = ModelengineB_G18 * p_u_h + ModelengineB_H18 * p_u_s
ModelengineB_O18 = excel_iferror(ModelengineB_K18/(1+discount_healthOutcome)^(ModelengineB_E18-1),"")
ModelengineB_G19 = ModelengineB_F19 * ModelengineB_G18 * p_hh_B
ModelengineB_H19 = ModelengineB_F19 * ( ModelengineB_G18 * p_hs_B + ModelengineB_H18 * p_ss_B )
ModelengineB_K19 = ModelengineB_G19 * p_u_h + ModelengineB_H19 * p_u_s
ModelengineB_O19 = excel_iferror(ModelengineB_K19/(1+discount_healthOutcome)^(ModelengineB_E19-1),"")
ModelengineB_G20 = ModelengineB_F20 * ModelengineB_G19 * p_hh_B
ModelengineB_H20 = ModelengineB_F20 * ( ModelengineB_G19 * p_hs_B + ModelengineB_H19 * p_ss_B )
ModelengineB_K20 = ModelengineB_G20 * p_u_h + ModelengineB_H20 * p_u_s
ModelengineB_O20 = excel_iferror(ModelengineB_K20/(1+discount_healthOutcome)^(ModelengineB_E20-1),"")
ModelengineB_G21 = ModelengineB_F21 * ModelengineB_G20 * p_hh_B
ModelengineB_H21 = ModelengineB_F21 * ( ModelengineB_G20 * p_hs_B + ModelengineB_H20 * p_ss_B )
ModelengineB_K21 = ModelengineB_G21 * p_u_h + ModelengineB_H21 * p_u_s
ModelengineB_O21 = excel_iferror(ModelengineB_K21/(1+discount_healthOutcome)^(ModelengineB_E21-1),"")
ModelengineB_G22 = ModelengineB_F22 * ModelengineB_G21 * p_hh_B
ModelengineB_H22 = ModelengineB_F22 * ( ModelengineB_G21 * p_hs_B + ModelengineB_H21 * p_ss_B )
ModelengineB_K22 = ModelengineB_G22 * p_u_h + ModelengineB_H22 * p_u_s
ModelengineB_O22 = excel_iferror(ModelengineB_K22/(1+discount_healthOutcome)^(ModelengineB_E22-1),"")
p_c_A = Modelparameters_R25
p_c_B = Modelparameters_R26
p_c_h = Modelparameters_R23
p_c_s = Modelparameters_R24
ModelengineA_O9 = excel_sum(list(ModelengineA_O12, ModelengineA_O13, ModelengineA_O14, ModelengineA_O15, ModelengineA_O16, ModelengineA_O17, ModelengineA_O18, ModelengineA_O19, ModelengineA_O20, ModelengineA_O21, ModelengineA_O22))
ModelengineA_I12 = ModelengineA_G12 * p_c_A
ModelengineA_J12 = ModelengineA_G12 * p_c_h + ModelengineA_H12 * p_c_s
ModelengineA_M12 = ModelengineA_I12
ModelengineA_N12 = ModelengineA_J12
ModelengineA_I13 = ModelengineA_G13 * p_c_A
ModelengineA_J13 = ModelengineA_G13 * p_c_h + ModelengineA_H13 * p_c_s
ModelengineA_M13 = excel_iferror(ModelengineA_I13/(1+discount_cost)^(ModelengineA_E13-1),"")
ModelengineA_N13 = excel_iferror(ModelengineA_J13/(1+discount_cost)^(ModelengineA_E13-1),"")
ModelengineA_I14 = ModelengineA_G14 * p_c_A
ModelengineA_J14 = ModelengineA_G14 * p_c_h + ModelengineA_H14 * p_c_s
ModelengineA_M14 = excel_iferror(ModelengineA_I14/(1+discount_cost)^(ModelengineA_E14-1),"")
ModelengineA_N14 = excel_iferror(ModelengineA_J14/(1+discount_cost)^(ModelengineA_E14-1),"")
ModelengineA_I15 = ModelengineA_G15 * p_c_A
ModelengineA_J15 = ModelengineA_G15 * p_c_h + ModelengineA_H15 * p_c_s
ModelengineA_M15 = excel_iferror(ModelengineA_I15/(1+discount_cost)^(ModelengineA_E15-1),"")
ModelengineA_N15 = excel_iferror(ModelengineA_J15/(1+discount_cost)^(ModelengineA_E15-1),"")
ModelengineA_I16 = ModelengineA_G16 * p_c_A
ModelengineA_J16 = ModelengineA_G16 * p_c_h + ModelengineA_H16 * p_c_s
ModelengineA_M16 = excel_iferror(ModelengineA_I16/(1+discount_cost)^(ModelengineA_E16-1),"")
ModelengineA_N16 = excel_iferror(ModelengineA_J16/(1+discount_cost)^(ModelengineA_E16-1),"")
ModelengineA_I17 = ModelengineA_G17 * p_c_A
ModelengineA_J17 = ModelengineA_G17 * p_c_h + ModelengineA_H17 * p_c_s
ModelengineA_M17 = excel_iferror(ModelengineA_I17/(1+discount_cost)^(ModelengineA_E17-1),"")
ModelengineA_N17 = excel_iferror(ModelengineA_J17/(1+discount_cost)^(ModelengineA_E17-1),"")
ModelengineA_I18 = ModelengineA_G18 * p_c_A
ModelengineA_J18 = ModelengineA_G18 * p_c_h + ModelengineA_H18 * p_c_s
ModelengineA_M18 = excel_iferror(ModelengineA_I18/(1+discount_cost)^(ModelengineA_E18-1),"")
ModelengineA_N18 = excel_iferror(ModelengineA_J18/(1+discount_cost)^(ModelengineA_E18-1),"")
ModelengineA_I19 = ModelengineA_G19 * p_c_A
ModelengineA_J19 = ModelengineA_G19 * p_c_h + ModelengineA_H19 * p_c_s
ModelengineA_M19 = excel_iferror(ModelengineA_I19/(1+discount_cost)^(ModelengineA_E19-1),"")
ModelengineA_N19 = excel_iferror(ModelengineA_J19/(1+discount_cost)^(ModelengineA_E19-1),"")
ModelengineA_I20 = ModelengineA_G20 * p_c_A
ModelengineA_J20 = ModelengineA_G20 * p_c_h + ModelengineA_H20 * p_c_s
ModelengineA_M20 = excel_iferror(ModelengineA_I20/(1+discount_cost)^(ModelengineA_E20-1),"")
ModelengineA_N20 = excel_iferror(ModelengineA_J20/(1+discount_cost)^(ModelengineA_E20-1),"")
ModelengineA_I21 = ModelengineA_G21 * p_c_A
ModelengineA_J21 = ModelengineA_G21 * p_c_h + ModelengineA_H21 * p_c_s
ModelengineA_M21 = excel_iferror(ModelengineA_I21/(1+discount_cost)^(ModelengineA_E21-1),"")
ModelengineA_N21 = excel_iferror(ModelengineA_J21/(1+discount_cost)^(ModelengineA_E21-1),"")
ModelengineA_I22 = ModelengineA_G22 * p_c_A
ModelengineA_J22 = ModelengineA_G22 * p_c_h + ModelengineA_H22 * p_c_s
ModelengineA_M22 = excel_iferror(ModelengineA_I22/(1+discount_cost)^(ModelengineA_E22-1),"")
ModelengineA_N22 = excel_iferror(ModelengineA_J22/(1+discount_cost)^(ModelengineA_E22-1),"")
ModelengineB_O9 = excel_sum(list(ModelengineB_O12, ModelengineB_O13, ModelengineB_O14, ModelengineB_O15, ModelengineB_O16, ModelengineB_O17, ModelengineB_O18, ModelengineB_O19, ModelengineB_O20, ModelengineB_O21, ModelengineB_O22))
ModelengineB_I12 = ModelengineB_G12 * p_c_B
ModelengineB_J12 = ModelengineB_G12 * p_c_h + ModelengineB_H12 * p_c_s
ModelengineB_M12 = ModelengineB_I12
ModelengineB_N12 = ModelengineB_J12
ModelengineB_I13 = ModelengineB_G13 * p_c_B
ModelengineB_J13 = ModelengineB_G13 * p_c_h + ModelengineB_H13 * p_c_s
ModelengineB_M13 = excel_iferror(ModelengineB_I13/(1+discount_cost)^(ModelengineB_E13-1),"")
ModelengineB_N13 = excel_iferror(ModelengineB_J13/(1+discount_cost)^(ModelengineB_E13-1),"")
ModelengineB_I14 = ModelengineB_G14 * p_c_B
ModelengineB_J14 = ModelengineB_G14 * p_c_h + ModelengineB_H14 * p_c_s
ModelengineB_M14 = excel_iferror(ModelengineB_I14/(1+discount_cost)^(ModelengineB_E14-1),"")
ModelengineB_N14 = excel_iferror(ModelengineB_J14/(1+discount_cost)^(ModelengineB_E14-1),"")
ModelengineB_I15 = ModelengineB_G15 * p_c_B
ModelengineB_J15 = ModelengineB_G15 * p_c_h + ModelengineB_H15 * p_c_s
ModelengineB_M15 = excel_iferror(ModelengineB_I15/(1+discount_cost)^(ModelengineB_E15-1),"")
ModelengineB_N15 = excel_iferror(ModelengineB_J15/(1+discount_cost)^(ModelengineB_E15-1),"")
ModelengineB_I16 = ModelengineB_G16 * p_c_B
ModelengineB_J16 = ModelengineB_G16 * p_c_h + ModelengineB_H16 * p_c_s
ModelengineB_M16 = excel_iferror(ModelengineB_I16/(1+discount_cost)^(ModelengineB_E16-1),"")
ModelengineB_N16 = excel_iferror(ModelengineB_J16/(1+discount_cost)^(ModelengineB_E16-1),"")
ModelengineB_I17 = ModelengineB_G17 * p_c_B
ModelengineB_J17 = ModelengineB_G17 * p_c_h + ModelengineB_H17 * p_c_s
ModelengineB_M17 = excel_iferror(ModelengineB_I17/(1+discount_cost)^(ModelengineB_E17-1),"")
ModelengineB_N17 = excel_iferror(ModelengineB_J17/(1+discount_cost)^(ModelengineB_E17-1),"")
ModelengineB_I18 = ModelengineB_G18 * p_c_B
ModelengineB_J18 = ModelengineB_G18 * p_c_h + ModelengineB_H18 * p_c_s
ModelengineB_M18 = excel_iferror(ModelengineB_I18/(1+discount_cost)^(ModelengineB_E18-1),"")
ModelengineB_N18 = excel_iferror(ModelengineB_J18/(1+discount_cost)^(ModelengineB_E18-1),"")
ModelengineB_I19 = ModelengineB_G19 * p_c_B
ModelengineB_J19 = ModelengineB_G19 * p_c_h + ModelengineB_H19 * p_c_s
ModelengineB_M19 = excel_iferror(ModelengineB_I19/(1+discount_cost)^(ModelengineB_E19-1),"")
ModelengineB_N19 = excel_iferror(ModelengineB_J19/(1+discount_cost)^(ModelengineB_E19-1),"")
ModelengineB_I20 = ModelengineB_G20 * p_c_B
ModelengineB_J20 = ModelengineB_G20 * p_c_h + ModelengineB_H20 * p_c_s
ModelengineB_M20 = excel_iferror(ModelengineB_I20/(1+discount_cost)^(ModelengineB_E20-1),"")
ModelengineB_N20 = excel_iferror(ModelengineB_J20/(1+discount_cost)^(ModelengineB_E20-1),"")
ModelengineB_I21 = ModelengineB_G21 * p_c_B
ModelengineB_J21 = ModelengineB_G21 * p_c_h + ModelengineB_H21 * p_c_s
ModelengineB_M21 = excel_iferror(ModelengineB_I21/(1+discount_cost)^(ModelengineB_E21-1),"")
ModelengineB_N21 = excel_iferror(ModelengineB_J21/(1+discount_cost)^(ModelengineB_E21-1),"")
ModelengineB_I22 = ModelengineB_G22 * p_c_B
ModelengineB_J22 = ModelengineB_G22 * p_c_h + ModelengineB_H22 * p_c_s
ModelengineB_M22 = excel_iferror(ModelengineB_I22/(1+discount_cost)^(ModelengineB_E22-1),"")
ModelengineB_N22 = excel_iferror(ModelengineB_J22/(1+discount_cost)^(ModelengineB_E22-1),"")
Results_G12 = ModelengineA_O9
Results_G13 = ModelengineB_O9
ModelengineA_M9 = excel_sum(list(ModelengineA_M12, ModelengineA_M13, ModelengineA_M14, ModelengineA_M15, ModelengineA_M16, ModelengineA_M17, ModelengineA_M18, ModelengineA_M19, ModelengineA_M20, ModelengineA_M21, ModelengineA_M22))
ModelengineA_N9 = excel_sum(list(ModelengineA_N12, ModelengineA_N13, ModelengineA_N14, ModelengineA_N15, ModelengineA_N16, ModelengineA_N17, ModelengineA_N18, ModelengineA_N19, ModelengineA_N20, ModelengineA_N21, ModelengineA_N22))
ModelengineB_M9 = excel_sum(list(ModelengineB_M12, ModelengineB_M13, ModelengineB_M14, ModelengineB_M15, ModelengineB_M16, ModelengineB_M17, ModelengineB_M18, ModelengineB_M19, ModelengineB_M20, ModelengineB_M21, ModelengineB_M22))
ModelengineB_N9 = excel_sum(list(ModelengineB_N12, ModelengineB_N13, ModelengineB_N14, ModelengineB_N15, ModelengineB_N16, ModelengineB_N17, ModelengineB_N18, ModelengineB_N19, ModelengineB_N20, ModelengineB_N21, ModelengineB_N22))
Results_F12 = ModelengineA_M9 + ModelengineA_N9
Results_H12 = Results_G12 * willingness_to_pay - Results_F12
Results_F13 = ModelengineB_M9 + ModelengineB_N9
Results_H13 = Results_G13 * willingness_to_pay - Results_F13
psafile <- 'test/excel workbook//psa.txt'
PSA_output <- PSA_output(psafile, dec = '.',Results_F12,Results_F13,Results_G12,Results_G13,Results_H12,Results_H13)
